# locate at ~/.config/alacritty/alacritty.toml

[general]
live_config_reload = true

# theme: https://github.com/alacritty/alacritty-theme
# import = [
#   # "~/.config/alacritty/themes/themes/everforest_dark.toml",
#   "~/.config/alacritty/themes/themes/gruvbox_dark.toml",
# ]


# fonts
[font]
size = 13
[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold"
[font.bold_italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold Italic"
[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"
[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.9
blur = true
# startup_mode = "Maximized"
# decorations = "Buttonless"
# decorations = "Transparent"
# padding = { x = 10, y = 30 }
# dynamic_padding = true
dimensions = { columns = 130, lines = 66 }


[cursor]
# style = { shape = "Block", blinking = "On" }

[keyboard]
bindings = [
    # spawn a new instance in the current working directory
    # (a new instance with default directory on MacOS)
    { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
]


# [env]
# TERM = "tmux-256color"

[terminal]
# managed by nix
# shell =  { program = "/run/current-system/sw/bin/fish", args = ["-l",]}
shell =  { program = "/opt/homebrew/bin/fish", args = ["-l",]}


# # https://github.com/alacritty/alacritty-theme/blob/master/themes/gruvbox_material_hard_dark.toml
# # Colors (Gruvbox Material Hard Dark)
# # Default colors
# [colors.primary]
# background = '#1d2021'
# foreground = '#d4be98'
# # Normal colors
# [colors.normal]
# black   = '#32302f'
# red     = '#ea6962'
# green   = '#a9b665'
# yellow  = '#d8a657'
# blue    = '#7daea3'
# magenta = '#d3869b'
# cyan    = '#89b482'
# white   = '#d4be98'
# # Bright colors (same as normal colors)
# [colors.bright]
# black   = '#32302f'
# red     = '#ea6962'
# green   = '#a9b665'
# yellow  = '#d8a657'
# blue    = '#7daea3'
# magenta = '#d3869b'
# cyan    = '#89b482'
# white   = '#d4be98'

# https://github.com/alacritty/alacritty-theme/blob/master/themes/breeze.toml
# KDE Breeze (Ported from Konsole)
# Default colors
[colors.primary]
background = '#232627'
foreground = '#fcfcfc'
dim_foreground = '#eff0f1'
bright_foreground = '#ffffff'
# Normal colors
[colors.normal]
black = '#232627'
red = '#ed1515'
green = '#11d116'
yellow = '#f67400'
blue = '#1d99f3'
magenta = '#9b59b6'
cyan = '#1abc9c'
white = '#fcfcfc'
# Bright colors
[colors.bright]
black = '#7f8c8d'
red = '#c0392b'
green = '#1cdc9a'
yellow = '#fdbc4b'
blue = '#3daee9'
magenta = '#8e44ad'
cyan = '#16a085'
white = '#ffffff'
# Dim colors
[colors.dim]
black = '#31363b'
red = '#783228'
green = '#17a262'
yellow = '#b65619'
blue = '#1b668f'
magenta = '#614a73'
cyan = '#186c60'
white = '#63686d'

